name: attendance_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.25.4
  http: ^1.2.0
  dio: ^5.4.0
  firebase_auth: ^4.17.4
  google_fonts: ^6.1.0
  email_validator: ^2.1.17
  network_info_plus: ^4.1.0+1
  permission_handler: ^11.2.1
  ez_validator: ^0.3.3
  art_sweetalert: ^0.0.5

dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

